### ISSUE TITLE
Creating a high score tracker

### ISSUE THREAD

**Issue by PhillipKP** [PhillipKP/congenial-spoon#3]
This would be a good exercise because it teaches your how to write to files, load files, and parse data stored in files.

**Comment by PhillipKP** [comment]
Breaking the problem down:
- Count the number of guesses
- Ask user for input if the user is in the top 10 scores (aka top 10 lowest number of guesses)
- We need to learn how to open text files. 
- We need to learn to read the open text files.
- We need to parse the data from the opened text files.
- Data stored in the file:
* 3 letter initials and score (aka number of guesses)
- Displaying the data on a screen.
- How to break a tie if two or more scores are the same.

**Comment by PhillipKP** [comment]
- [x] First we need to ask the user to enter their initials (up to 3 letters) then use regex to check for legit characters and is only 3 characters.

**Comment by PhillipKP** [comment]
- [x] Get the number of guesses
- [x] Get the date and time as a string variable
- [x] Concatenate the initials, the date and time, and number of guesses into a comma separated string. 
- [x] Write that string to file as a comma delimiters
- [x] Open that file
- [x] Parse the file
- [x] Split a string by commas
- [x] Insert the split strings aka sub-strings into a vector of structs for sorting.
- [x] Figure out how to line up the columns when printing out the high scores for cases when there is only 2 initials
- [ ] Compute scores that in the top 10
- [ ] Displays scores that are in the top 10
- [ ] Throws away scores that are not in the top 10
- [ ] Display the people with the lowest guess
